[env:guition_smart_display]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Memory Configuration for Octal PSRAM (N16R8 variant)
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L

board_build.flash_mode = qio

build_flags = 
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_SPEED_80M=1
    ; Standard LVGL Settings
    -DLV_CONF_INCLUDE_SIMPLE
    -I src
    -DLV_COLOR_DEPTH=16
    -DLV_FONT_MONTSERRAT_12=1
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_48=1
    ; Disable architecture-specific ASM for Xtensa
    -DLV_USE_NATIVE_HELIUM_ASM=0
    -DLV_USE_NATIVE_ARM32_ASM=0
    -DLV_USE_NATIVE_ARM64_ASM=0
    -DLV_USE_NATIVE_NEON_ASM=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=0

lib_deps =
    lovyan03/LovyanGFX @ ^1.2.7
    lvgl/lvgl @ ^9.3.0
    bblanchon/ArduinoJson @ ^7.3.0
    https://github.com/tzapu/WiFiManager.git
monitor_speed = 115200
